project:
  type: website

website:
  title: "scup"
  description: "Your go-to for catching up with everything single-cell related."
  site-url: https://scup.netlify.app
  repo-url: https://github.com/mdmanurung/scup
  open-graph: true
  twitter-card:
    creator: "@mikhaeldito313"
    card-style: summary_large_image
  navbar:
    background: "#eeeeee"
    right:
      - text: "by Mikhael D. Manurung"
        href: https://mdmanurung.rbind.io
      - about.qmd
      - icon: github
        aria-label: github
        href: https://github.com/mdmanurung
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/mikhaeldito313

format:
  html:
    theme: ember.scss
    css: styles.css
    include-after-body: footer.html

editor: visual

execute:
  freeze: auto
